# Generated by Django 4.2.13 on 2024-06-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcampaign', '0002_alter_webcampaignurl_options_webcampaignurl_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcampaignurl',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='webcampaignurl',
            name='utm_id',
        ),
    ]
