# Generated by Django 4.2.13 on 2024-06-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='landline',
            new_name='companyWebSite',
        ),
    ]
