# Generated by Django 4.2.13 on 2024-06-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayCampaignUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_network', models.CharField(max_length=100)),
                ('application_id', models.CharField(max_length=100)),
                ('campaign_source', models.CharField(max_length=100)),
                ('campaign_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_term', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_content', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'PlayCampaignUrl',
                'verbose_name_plural': 'PlayCampaignUrls',
            },
        ),
    ]
