# Generated by Django 4.2.13 on 2024-06-20 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playcampaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playcampaignurl',
            options={'verbose_name': 'Play Campaign Url', 'verbose_name_plural': 'Play Campaign Urls'},
        ),
        migrations.AddField(
            model_name='playcampaignurl',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
